name: test
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^1.0.0-dev.11
  freezed_annotation: ^0.14.3
  flutter_svg: ^0.22.0
  build_runner: ^2.1.2
  freezed: ^0.14.5
  json_serializable:
  http_parser: ^4.0.0
  dio: ^4.0.0
  audio_video_progress_bar: ^0.9.0
  rxdart: ^0.27.2
  just_audio: ^0.9.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  assets:
    - assets/
  uses-material-design: true
